const quotes = [
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. - Helen Keller",
    "The difference between ordinary and extraordinary is that little extra. - Jimmy Johnson",
    "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. So throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails. Explore, Dream, Discover. - Mark Twain",
    "It is during our darkest moments that we must focus to see the light. - Aristotle",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The mind is everything. What you think you become. - Buddha",
    "The journey of a thousand miles begins with a single step. - Lao Tzu",
    "Doubt kills more dreams than failure ever will. - Suzy Kassem",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Insanity is doing the same thing over and over again and expecting different results. - Albert Einstein",
    "We are all faced with a series of great opportunities brilliantly disguised as impossible situations. - Charles R. Swindoll",
    "If you can dream it, you can do it. - Walt Disney",
    "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. - Steve Jobs",
    "The mind is not a vessel to be filled, but a fire to be ignited. - Plutarch",
    "There is no substitute for hard work. - Thomas Edison",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Curiosity about life in all its aspects, I think, is still the secret of great creative people. - Leo Burnett",
    "Innovation distinguishes between a leader and a follower. - Steve Jobs",
    "Creativity is intelligence having fun. - Albert Einstein",
    "The important thing is not to stop questioning. Curiosity has its own reason for existing. - Albert Einstein",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. - Helen Keller",
    "If you can dream it, you can do it. - Walt Disney",
    "The mind is not a vessel to be filled, but a fire to be ignited. - Plutarch",
    "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. - Steve Jobs",
    "Curiosity about life in all its aspects, I think, is still the secret of great creative people. - Leo Burnett",
    "Innovation distinguishes between a leader and a follower. - Steve Jobs",
    "Creativity is intelligence having fun. - Albert Einstein",
    "The important thing is not to stop questioning. Curiosity has its own reason for existing. - Albert Einstein",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "Change is the only constant in life. - Heraclitus",
    "Education is the most powerful weapon which you can use to change the world. - Nelson Mandela",
    "The unexamined life is not worth living. - Socrates",
    "Difficulties in your life are intended to make you, not break you. - Roy T. Bennett",
    "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence. - Helen Keller",
    "The best revenge is massive success. - Frank Sinatra",
    "You may not control all the events that happen to you, but you can decide not to be reduced by them. - Maya Angelou",
    "Life is 10% what happens to me and 90% how I react to it. - Charles R. Swindoll",
    "Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma - which is living with the results of other people"
] 

exports.quotes = quotes;